### ISSUE TITLE
Auto-derived impl doesn't take into account type parameters

### ISSUE THREAD

**Issue by XMPPwocky** [sunng87/tojson_macros#1]
Something like

``` rust
#[derive(ToJson)]
struct Foo<T: ToJson> {
    x: T
}
```

fails to compile. With other derived things (like PartialEq, Clone, etc.), this works.

**Comment by gyscos** [comment]
It seems that it similarly doesn't take into account lifetime parameters? Or is that a separate bug?

``` rust
#[derive(ToJson)]
struct Foo<'a> {
    x: &'a str,
}
```

**Comment by sunng87** [comment]
Seems some modifiers are missing in code generation. Will look into this issue when I get time. Thanks for using and reporting!
